### ISSUE TITLE
Introspection endpoint will never be accessed

### ISSUE THREAD

**Issue by helmut72** [bploetz/caddy-oauth2-token-introspection#1]
First, thanks for this interesting addon!

I've tried it, used your example, but the introspection endpoint will never be accessed. That's all:

```
{"level":"debug","ts":1667069922.8714907,"logger":"http.handlers.oauth2_token_introspection","msg":"authorizing request"}
{"level":"debug","ts":1667069922.8716848,"logger":"http.handlers.oauth2_token_introspection","msg":"getting token from 'Authorization: Bearer' header"}
[Oct 29 18:58:42] error 1.2.3.4 test.example.com - "GET /private HTTP/3.0" 401 ["Mozilla/5.0 (Macintosh; Intel Mac OS X ...)]
```

This is my config for oauth2:

```
(oauth2_protected) {
	oauth2_token_introspection {
		token_location bearer_token
		introspection_endpoint https://auth.example.com/oauth/v2/introspect
		introspection_authentication_strategy client_credentials
		introspection_client_id my_client_id
		introspection_client_secret my_very_secure_secret
		introspection_timeout 1000
		set_header X-API-GATEWAY-SCOPE scope
		set_header X-API-GATEWAY-SUBJECT sub
		set_header X-API-GATEWAY-EMAIL-ADDRESS email
	}
}
```

And a backend for testing:

```
test.example.com:443 {
	import wildcard
	import client_headers
	import log_formatted INFO

	@protected_paths {
		path /private
		path /very-private
	}
	route {
		import oauth2_protected
		reverse_proxy @protected_paths http://172.17.1.1:2000   # <- there is just a whoami docker image running, showing all headers
	}
}
```

I'm using Caddy 2.6.2

Am I right, that at least a request must be seen in the logs to `https://auth.example.com/oauth/v2/introspect`, doesn't matter if it's a valid url or not? But there is no request to auth.example.com.

**Comment by bploetz** [comment]
Hey @helmut72. Your Caddyfile has:

```
introspection_endpoint https://auth.example.com/oauth/v2/introspect
```

That can't be the actual introspection endpoint you're using, as that's not a real host. When I use that host I get:

```
caddy_1  | 1.6670757128949387e+09	error	http.handlers.oauth2_token_introspection	error performing token introspection. Post "https://auth.example.com/oauth/v2/introspect": dial tcp: lookup auth.example.com on 127.0.0.11:53: no such host
```

So I assume you're using a real introspection endpoint and this was just an example.

Anyhow, can you include the exact request you're making to Caddy, including the headers? I just noticed that when the `oauth2_token_introspection` config has `token_location bearer_token` and you don't actually pass a `Authorization: Bearer <my token>` HTTP header, the caddy-oauth2-token-introspection module will not print out  a debug statement that it can't find the header, it will just return a 401 status code.

Example request:
```
curl -vv -H "Host: api.myhost.com"  -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:8080/v1/protected-endpoint

*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v1/protected-endpoint HTTP/1.1
> Host: api.myhost.com
> User-Agent: curl/7.79.1
> Accept: application/json
> Content-Type: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized                   <----------- HERE
< Date: Sat, 29 Oct 2022 20:43:58 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

Logs for that request:
```
caddy_1  | 1.667076238368348e+09	debug	http.handlers.oauth2_token_introspection	authorizing request
caddy_1  | 1.6670762383684053e+09	debug	http.handlers.oauth2_token_introspection	getting token from 'Authorization: Bearer' header
```

As you can see it doesn't print anything useful that it couldn't find the access token. I will fix this so it prints a debug statement that it couldn't find the access token, but in the mean time, let me know what your request looks like.

**Comment by helmut72** [comment]
> So I assume you're using a real introspection endpoint and this was just an example.

Yes, it's just an example. I don't write down any real domains I use.

> Anyhow, can you include the exact request you're making to Caddy, including the headers?

Thanks for writing down everything. Now it becomes clearer for me and I'm sure, I have misunderstood `oauth2_token_introspection`. I have only tried it with a browser, expected to be redirected to the IDP to login to get access to my secured site, sending username, email header.

Caddy includes forward auth module, but this is only supported for a few IDPs Then I thought to use your module. Sorry for the noise.
